# Generated by Django 3.2 on 2021-05-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_application_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Year_of_study',
            field=models.IntegerField(),
        ),
    ]
