# Generated by Django 3.2 on 2021-05-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_application_year_of_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Expected_Graduation_Year',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cgpa',
        ),
        migrations.AlterField(
            model_name='application',
            name='Sop',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='Transcript',
            field=models.FileField(upload_to=''),
        ),
    ]
